add new failsafes

diff --git a/bin/detach-deployment-unit-from-lb b/bin/detach-deployment-unit-from-lb
--- a/bin/detach-deployment-unit-from-lb
+++ b/bin/detach-deployment-unit-from-lb
@@ -39,11 +39,12 @@ load-balancer disable-target-group \
     --product "$PRODUCT" \
     --az-abreviation="$AZ_ABREVIATION"
 
+if [ $? != 0 ]; then echo "DETACH FAILED!!! $PRODUCT on $CLUSTER_ID $COLOR load balancer is potentially unstable!" && exit 1; fi
+
 if [ "$COLOR" == blue ]
 then
   echo "Giving the blue load balancer time to catch up"
   sleep 60
 fi
 
-if [ $? != 0 ]; then echo "Detach did not succeed, proceeding anyway"; fi
 exit 0
