k8s deployment test Wed May 15 09:26:17 EDT 2019

diff --git a/bin/execute-tests b/bin/execute-tests
--- a/bin/execute-tests
+++ b/bin/execute-tests
@@ -31,3 +31,9 @@ docker run \
   $TEST_IMAGE \
   $TEST \
   | tee $LOG_DIR/$TEST-$AVAILABILITY_ZONE.log
+
+if [ $TEST == regression-test -a  $SIMULATE_REGRESSION_TEST_FAILURE == true ]
+then
+  echo "*** SIMULATING REGRESSION TEST FAILURE ***"
+  exit 1
+fi
