Cache the vpcId

diff --git a/bin/load-balancer b/bin/load-balancer
--- a/bin/load-balancer
+++ b/bin/load-balancer
@@ -122,7 +122,7 @@ targetGroupArn() {
   local tgName
   tgName=$(tgName) || exit 1
   local cached=$(cacheGet tg-arn-$tgName)
-  [ -n "$cached" ] && echo $cached
+  [ -n "$cached" ] && echo $cached && return
   local targetGroupArn=$(aws elbv2 describe-target-groups \
     --names "$tgName" \
     | jq -r '.TargetGroups[].TargetGroupArn')
@@ -254,13 +254,13 @@ createRule() {
       '.Rules[] | { ruleArn: .RuleArn, rulePriority: .Priority, rulePaths: .Conditions[].Values }' \
       $temp
   fi
-  
+
   if [ -n "$ruleArns" ]
   then
     echo "Removing old version of rule $RULE_PATH"
     for ruleArn in $ruleArns
     do
-      echo "Deleting rule $ruleArn"  
+      echo "Deleting rule $ruleArn"
       aws elbv2 delete-rule \
         --debug \
         --rule-arn "$ruleArn" \
@@ -550,11 +550,14 @@ listEnvironments() {
 VPC_ENV=
 VPC_ID= # automatically set based on VPC_ENV
 vpcId() {
-  [ -n "$VPC_ID" ] && echo $VPC_ID && return 0
-  VPC_ID=$(aws ec2 describe-vpcs --filters Name=tag:Environment,Values=$VPC_ENV | jq -r .Vpcs[].VpcId)
-  [ -z "$VPC_ID" ] && echo "Could not find VPC for environment $VPC_ENV" && exit 1
-  debug "VPC $VPC_ID ($VPC_ENV)"
+  local cached=$(cacheGet vpcId)
+  [ -n "$cached" ] && echo $cached && return
+  local vpcId=$(aws ec2 describe-vpcs --filters Name=tag:Environment,Values=$VPC_ENV | jq -r .Vpcs[].VpcId)
+  [ -z "$vpcId" ] && echo "Could not find VPC for environment $VPC_ENV" && exit 1
+  cachSet vpcId "$vpcId"
+  echo $vpcId
 }
+
 CLUSTER_ID=
 HEALTH_CHECK_INTERVAL=5
 HEALTH_CHECK_TIMEOUT=2
