return cache or get cache

diff --git a/bin/load-balancer b/bin/load-balancer
--- a/bin/load-balancer
+++ b/bin/load-balancer
@@ -122,12 +122,15 @@ targetGroupArn() {
   local tgName
   tgName=$(tgName) || exit 1
   local cached=$(cacheGet tg-arn-$tgName)
-  [ -n "$cached" ] && echo $cached && return
-  local targetGroupArn=$(aws elbv2 describe-target-groups \
-    --names "$tgName" \
-    | jq -r '.TargetGroups[].TargetGroupArn')
-  cacheSet "tg-arn-$tgName" "$targetGroupArn"
-  echo $targetGroupArn
+  if [ -n "$cached" ]; then
+    echo $cached
+  else
+    local targetGroupArn=$(aws elbv2 describe-target-groups \
+      --names "$tgName" \
+      | jq -r '.TargetGroups[].TargetGroupArn')
+    cacheSet "tg-arn-$tgName" "$targetGroupArn"
+    echo $targetGroupArn
+  fi
 }
 
 createTargetGroup() {
@@ -180,21 +183,27 @@ albName() {
 albArn() {
   local albName="$1"
   local cached=$(cacheGet "alb-arn-$albName")
-  [ -n "$cached" ] && echo "$cached" && return
-  local alb=$(aws elbv2 describe-load-balancers --names $albName \
-    | jq -r .LoadBalancers[].LoadBalancerArn)
-  cacheSet "alb-arn-$albName" "$alb"
-  echo "$alb"
+  if [ -n "$cached" ]; then
+    echo "$cached"
+  else
+    local alb=$(aws elbv2 describe-load-balancers --names $albName \
+      | jq -r .LoadBalancers[].LoadBalancerArn)
+    cacheSet "alb-arn-$albName" "$alb"
+    echo "$alb"
+  fi
 }
 
 albHttpsListener() {
   local alb="$1"
   local cached=$(cacheGet "https-$alb")
-  [ -n "$cached" ] && echo "$cached" && return
-  local listener=$(aws elbv2 describe-listeners --load-balancer-arn $alb \
-    | jq -r '.Listeners[] | select(.Protocol == "HTTPS").ListenerArn')
-  cacheSet "https-$alb" "$listener"
-  echo "$listener"
+  if [ -n "$cached" ]; then
+    echo "$cached"
+  else
+    local listener=$(aws elbv2 describe-listeners --load-balancer-arn $alb \
+      | jq -r '.Listeners[] | select(.Protocol == "HTTPS").ListenerArn')
+    cacheSet "https-$alb" "$listener"
+    echo "$listener"
+  fi
 }
 
 #
@@ -552,11 +561,14 @@ VPC_ID= # automatically set based on VPC_ENV
 vpcId() {
   local vpcCache="vpcId-$VPC_ENV"
   local cached=$(cacheGet $vpcCache)
-  [ -n "$cached" ] && echo $cached && return
-  local vpcId=$(aws ec2 describe-vpcs --filters Name=tag:Environment,Values=$VPC_ENV | jq -r .Vpcs[].VpcId)
-  [ -z "$vpcId" ] && echo "Could not find VPC for environment $VPC_ENV" && exit 1
-  cacheSet $vpcCache $vpcId
-  echo $vpcId
+  if [ -n "$cached" ]; then
+    echo $cached
+  else
+    local vpcId=$(aws ec2 describe-vpcs --filters Name=tag:Environment,Values=$VPC_ENV | jq -r .Vpcs[].VpcId)
+    [ -z "$vpcId" ] && echo "Could not find VPC for environment $VPC_ENV" && exit 1
+    cacheSet $vpcCache $vpcId
+    echo $vpcId
+  fi
 }
 
 CLUSTER_ID=
