development test Tue Jul 21 15:52:38 EDT 2020

diff --git a/bin/product-configuration b/bin/product-configuration
--- a/bin/product-configuration
+++ b/bin/product-configuration
@@ -86,8 +86,6 @@ copyConfiguration() {
   if [ ! -d $toDir ]; then mkdir -p $toDir; fi
   cp $fromDir/$product.yaml $toDir/product.yaml
   cat > $toDir/product.conf <<EOF
-echo Loading product configuration
-set -euo pipefail
 declare -x DU_ARTIFACT
 declare -x DU_VERSION
 EOF
@@ -96,7 +94,6 @@ cat >> $toDir/product.conf <<EOF
 foooooo
 if [ -z "\${DU_GROUP:-}" ]; then DU_GROUP=gov.va.api.health; fi
 if [ -z "\${DU_COORDINATES:-}" ]; then DU_COORDINATES="\$DU_GROUP:\$DU_ARTIFACT:tar.gz:product"; fi
-echo Done
 EOF
   validateConfiguration $toDir/product.conf
 }
@@ -110,20 +107,16 @@ fail() {
 validateConfiguration() {
   local conf="$1"
   echo "Validating product configuration"
-  if ! (
-      echo before
-      . $conf
-      echo $? after
-      if [ -z "$DU_ARTIFACT" ]; then fail "Missing DU_ARTIFACT"; fi
-      if [ -z "$DU_VERSION" ]; then fail "Missing DU_VERSION"; fi
-      if [ "${INVALID_PRODUCT_CONF:=false}" == "true" ]
-      then
-        echo "Invalid product configuration"
-        exit 1
-      fi
-    )
+  if ! . $conf
   then
     echo "Failed to load product configuration"
+    exit 1
+  fi
+  if [ -z "$DU_ARTIFACT" ]; then fail "Missing DU_ARTIFACT"; fi
+  if [ -z "$DU_VERSION" ]; then fail "Missing DU_VERSION"; fi
+  if [ "${INVALID_PRODUCT_CONF:=false}" == "true" ]
+  then
+    echo "Invalid product configuration"
     exit 1
   fi
 }
