Better Logging

diff --git a/bin/ryan-secrets b/bin/ryan-secrets
--- a/bin/ryan-secrets
+++ b/bin/ryan-secrets
@@ -2,7 +2,10 @@
 
 set -euo pipefail
 
+# Encryption always uses the latest method
 ENCRYPTION_VERSION=2
+# Decryption is determined during decryption phase
+DECRYPTION_VERSION=""
 
 #~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~
 
@@ -13,11 +16,11 @@ usage() {
   ^(export )?([-A-Za-z0-9_]+=)(.*)
 
   Commands
-    encrypt [--file|-f <file>] [--encryption-passphrase|-e <passphrase>]
-    decrypt [--file|-f <file>] [--encryption-passphrase|-e <passphrase>]
+    encrypt [--file|-f <file>] [--encryption-passphrase|-e <passphrase>] [--version|-v <version>]
+    decrypt [--file|-f <file>] [--encryption-passphrase|-e <passphrase>] [--version|-v <version>]
       Encrypt or decrypt a single file
-    encrypt-all [--directory|-d <directory>] [--encryption-passphrase|-e <passphrase>]
-    decrypt-all [--directory|-d <directory>] [--encryption-passphrase|-e <passphrase>]
+    encrypt-all [--directory|-d <directory>] [--encryption-passphrase|-e <passphrase>] [--version|-v <version>]
+    decrypt-all [--directory|-d <directory>] [--encryption-passphrase|-e <passphrase>] [--version|-v <version>]
       Encrypt or decrypt a deployment unit directory. Environment conf and testvars files will be processed.
 
   Example
@@ -46,6 +49,7 @@ main() {
       -d|--directory) DIRECTORY=${2%/};;
       -e|--encryption-passphrase) ENCRYPTION_PASSPHRASE="$2";;
       -f|--file) FILE=$2;;
+      -v|--version) ENCRYPTION_VERSION=$2; DECRYPTION_VERSION=$2;;
       -h|--help) usage;;
       --) shift;break;;
     esac
@@ -69,14 +73,17 @@ main() {
 #~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~
 
 allFiles() {
+  local tmpLog=$(mktemp)
   local action="${1:-}"
 
   echo "${action}ing .conf and .testvars files..."
   for file in $(findFiles)
   do
     echo "${action}ing $file"
-    $action $file
+    $action $file > $tmpLog
+    cat $tmpLog | uniq
   done
+  rm $tmpLog
 }
 
 checkFile() {
@@ -136,7 +143,7 @@ encryption() {
   esac
 
   local launcher=$(nativeOrDocker)
-  returnValue=$(echo -E "${secret}" | ${launcher} ${doEncryption})
+  returnValue=$(echo -E "${secret}" | ${launcher} ${doEncryption} 2> /dev/null)
   returnStatus=$?
 
   echo "$returnValue"
@@ -158,7 +165,7 @@ encrypt() {
       local secret
       if ! secret=$(encryption ${ENCRYPTION_VERSION} encrypt "${BASH_REMATCH[3]}")
       then
-        logError "Encrypt Failed." && exit 1
+        logError "ERROR: Encryption Failed." && exit 1
       fi
       echo -E "${BASH_REMATCH[1]}${BASH_REMATCH[2]}${secret}" >> $out
     elif [[ "$line" =~ ^#decrypted ]]
@@ -183,14 +190,16 @@ decrypt(){
     if [[ "$line" =~ ^(export )?([-A-Za-z0-9_]+=)(.*) ]]
     then
       local unsecret
-      for ((i = ${ENCRYPTION_VERSION}; i >= 1; i--)); do
+      for ((i = ${DECRYPTION_VERSION:-${ENCRYPTION_VERSION}}; i >= 1; i--)); do
         if unsecret=$(encryption ${i} decrypt "${BASH_REMATCH[3]}")
         then
+          setDecryptionVersion ${i}
+          [ "${i}" == "1" ] && echo "WARN:  Version 1 decryption detected. Please upgrade."
           break
         else
-          logError "Decrypt v${i} Failed."
+          logError "WARN:  Decrypt v${i} Failed."
           # That's all folks.
-          [ "${i}" == "1" ] && logError "Failed to Decrypt." && exit 1
+          [ "${i}" == "1" ] && logError "ERROR: Failed to Decrypt." && exit 1
           continue
         fi
       done
@@ -198,10 +207,7 @@ decrypt(){
     elif [[ "$line" =~ ^#encrypted ]]
     then
       # Should always exist once on the top line
-      local encryptVersion=$(echo "$line" | awk '{print $2}')
-      [ -n "${encryptVersion}" ] \
-        && ENCRYPTION_VERSION="${encryptVersion}" \
-        && echo "Found Encryption Version ${encryptVersion}"
+      setDecryptionVersion $(echo "$line" | awk '{print $2}')
       echo -E '#decrypted' >> $out
     else
       echo -E "$line" >> $out
@@ -213,6 +219,14 @@ decrypt(){
 
 logError() {
   echo "$@" >&2
+}
+
+setDecryptionVersion() {
+  local value="${1:-}"
+  if [ -z "${DECRYPTION_VERSION:-}" ] && [ -n "${value}" ]; then
+    DECRYPTION_VERSION="${value}"
+    echo "INFO:  Determined Decryption Version ${DECRYPTION_VERSION}."
+  fi
 }
 
 #~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~
