Separate encryption type specific things

diff --git a/bin/ryan-secrets b/bin/ryan-secrets
--- a/bin/ryan-secrets
+++ b/bin/ryan-secrets
@@ -2,6 +2,8 @@
 
 set -euo pipefail
 
+ENCRYPTION_VERSION=2
+
 #~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~
 
 usage() {
@@ -98,35 +100,33 @@ findFiles() {
 }
 
 encryption() {
-  local version=$(echo "${1:-}" | sed 's/v\([0-9]*\)/\1/')
+  local returnStatus returnValue
+  local version=${1:-}
   local action=${2:-}
   shift; shift
   local secret="$@"
-  
-  local encodeOpt
+
+  # Args specific to the action being performed
+  local opensslOpt
   case "${action}" in
-    encrypt) encodeOpt="-e";;
-    decrypt) encodeOpt="-d";;
+    encrypt) opensslOpt="-e";;
+    decrypt) opensslOpt="-d";;
+    *) logError "Invalid Encryption Type: ${action}"; exit 1;;
   esac
 
-  local finalValue
-  for ((i = ${version}; i >= 1; i--)); do
-    finalValue=$(echo -E "${secret}" | openssl enc ${encodeOpt:-} $(getEncryptionOptionsForVersion "${i}"))
-    if [ "$?" != 0 ] && [ "${action}" == "decrypt" ]; then
-      continue
-    fi
-    break
-  done
-  
-  echo $finalValue
-}
-
-getEncryptionOptionsForVersion() {
-  local version=${1:-}
+  # Encryption Command
+  local doEncryption
   case "${version}" in
-    1) echo "-aes-256-cbc -md md5 -a -A -nosalt -k ${ENCRYPTION_PASSPHRASE}";;
-    2) echo "-aes-256-cbc -md md5 -pbkdf2 -iter 1000 -a -A -nosalt -k ${ENCRYPTION_PASSPHRASE}";;
+    1) doEncryption="openssl enc -aes-256-cbc -md md5 -a -A -nosalt -k ${ENCRYPTION_PASSPHRASE} ${opensslOpt}";;
+    2) doEncryption="openssl enc -aes-256-cbc -md md5 -pbkdf2 -iter 1000 -a -A -nosalt -k ${ENCRYPTION_PASSPHRASE} ${opensslOpt}";;
+    *) logError "Invalid Encryption Version: ${version}"; exit 1;;
   esac
+  
+  returnValue=$(echo -E "${secret}" | ${doEncryption})
+  returnStatus=$?
+  
+  echo $returnValue
+  return $returnStatus
 }
 
 encrypt() {
@@ -139,7 +139,10 @@ encrypt() {
   do
     if [[ "$line" =~ ^(export )?([-A-Za-z0-9_]+=)(.*) ]]
     then
-      local secret=$(encryption v2 encrypt "${BASH_REMATCH[3]}")
+      local secret
+      if ! secret=$(encryption ${ENCRYPTION_VERSION} encrypt "${BASH_REMATCH[3]}"); then
+        [ "$?" != "0" ] && logError "Encrypt Failed." && exit 1
+      fi
       echo -E "${BASH_REMATCH[1]}${BASH_REMATCH[2]}$secret" >> $out
     elif [[ "$line" =~ ^#decrypted ]]
       then
@@ -160,7 +163,17 @@ decrypt(){
   do
     if [[ "$line" =~ ^(export )?([-A-Za-z0-9_]+=)(.*) ]]
     then
-      local unsecret=$(encryption v2 decrypt "${BASH_REMATCH[3]}")
+      local unsecret
+      for ((i = ${ENCRYPTION_VERSION}; i >= 1; i--)); do  
+        if unsecret=$(encryption ${i} decrypt "${BASH_REMATCH[3]}"); then
+          break
+        else  
+          logError "Decrypt v${i} Failed."
+          # That's all folks.  
+          [ "${i}" == "1" ] && logError "Failed to Decrypt." && exit 1
+          continue
+        fi
+      done
       echo -E "${BASH_REMATCH[1]}${BASH_REMATCH[2]}$unsecret" >> $out
     elif [[ "$line" =~ ^#encrypted ]]
       then
@@ -171,6 +184,10 @@ decrypt(){
   done < "$file"
   cat $out > "$file"
   return
+}
+
+logError() {
+  echo "$@" >&2
 }
 
 #~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~
