Remove Case

diff --git a/bin/ryan-secrets b/bin/ryan-secrets
--- a/bin/ryan-secrets
+++ b/bin/ryan-secrets
@@ -103,7 +103,8 @@ encryption() {
   local returnStatus returnValue
   local version=${1:-}
   local action=${2:-}
-  shift; shift
+  shift
+  shift
   local secret="$@"
 
   # Args specific to the action being performed
@@ -141,7 +142,7 @@ encrypt() {
     then
       local secret
       if ! secret=$(encryption ${ENCRYPTION_VERSION} encrypt "${BASH_REMATCH[3]}"); then
-        [ "$?" != "0" ] && logError "Encrypt Failed." && exit 1
+        logError "Encrypt Failed." && exit 1
       fi
       echo -E "${BASH_REMATCH[1]}${BASH_REMATCH[2]}$secret" >> $out
     elif [[ "$line" =~ ^#decrypted ]]
