re-order validation tests

diff --git a/bin/validate-yaml b/bin/validate-yaml
--- a/bin/validate-yaml
+++ b/bin/validate-yaml
@@ -21,6 +21,11 @@ exit 1
 [ -z $FILE ] && echo "No deployment.yaml specified." && usage && exit 1
 [ -z $NAMESPACE ] && echo "No namespace specified." && usage && exit 1
 
+INGRESS_TEST=$(grep "kind: Ingress" $1)
+[[ ! -z "$INGRESS_TEST" ]] && echo "Ingress Validation Failed. Do NOT include ingress rules in deployment yamls!" && exit 1
+
+NAMESPACE_TEST=$(grep "kind: Namespace" $1)
+[[ ! -z "$NAMESPACE_TEST" ]] && echo "Namespace Test Validation Failed. Do NOT include Namespace creation in deployment yamls!" && exit 1
 
 NAMESPACE_STRUCT=$(grep -E '^.*(kind|metadata|  namespace):' $1)
 echo "$NAMESPACE_STRUCT" | while read line ; do
@@ -53,9 +58,3 @@ echo "$NAMESPACE_STRUCT" | while read line ; do
   fi
 
 done
-
-INGRESS_TEST=$(grep "kind: Ingress" $1)
-[[ ! -z "$INGRESS_TEST" ]] && echo "Ingress Validation Failed. Do NOT include ingress rules in deployment yamls!" && exit 1
-
-NAMESPACE_TEST=$(grep "kind: Namespace" $1)
-[[ ! -z "$NAMESPACE_TEST" ]] && echo "Namespace Test Validation Failed. Do NOT include Namespace creation in deployment yamls!" && exit 1
