better formatting

diff --git a/bin/validate-yaml b/bin/validate-yaml
--- a/bin/validate-yaml
+++ b/bin/validate-yaml
@@ -22,10 +22,14 @@ exit 1
 [ -z $NAMESPACE ] && echo "No namespace specified." && usage && exit 1
 
 INGRESS_TEST=$(grep "kind: Ingress" $1)
-[[ ! -z "$INGRESS_TEST" ]] && echo "Ingress Validation Failed. Do NOT include ingress rules in deployment yamls!" && exit 1
+[[ ! -z "$INGRESS_TEST" ]] && echo "==============================" \
+  && echo "Ingress Validation Failed. Do NOT include ingress rules in deployment yamls!" \
+  && exit 1
 
 NAMESPACE_TEST=$(grep "kind: Namespace" $1)
-[[ ! -z "$NAMESPACE_TEST" ]] && echo "Namespace Test Validation Failed. Do NOT include Namespace creation in deployment yamls!" && exit 1
+[[ ! -z "$NAMESPACE_TEST" ]] echo "==============================" \
+  && echo "Namespace Test Validation Failed. Do NOT include Namespace creation in deployment yamls!" \
+  && exit 1
 
 NAMESPACE_STRUCT=$(grep -E '^.*(kind|metadata|  namespace):' $1)
 echo "$NAMESPACE_STRUCT" | while read line ; do
@@ -33,12 +37,16 @@ echo "$NAMESPACE_STRUCT" | while read line ; do
   if [[ "$metadata" = true ]]; then
     if [[ "$line" == *"namespace"* ]]; then
       if [ $(echo "$line" | awk '{ print $2 }') != "$NAMESPACE" ]; then
-        echo "Namespace Validation Failed. Namespace should be: $2 but $line was found." && exit 1
+        echo "==============================" \
+          && echo "Namespace Validation Failed. Namespace should be: $2 but $line was found." \
+          && exit 1
       fi
       unset metadata
       continue
     else
-       echo "Namespace Validation Failed. Missing 'namespace:' field following a 'metadata' field." && exit 1
+      echo "==============================" \
+        && echo "Namespace Validation Failed. Missing 'namespace:' field following a 'metadata' field." \
+        && exit 1
     fi
   fi
 
@@ -48,7 +56,9 @@ echo "$NAMESPACE_STRUCT" | while read line ; do
       metadata=true
       continue
     else
-    echo "Metadata Validation Failed. Missing 'metadata' field following a 'kind' field." && exit 1
+      echo "==============================" \
+      && echo "Metadata Validation Failed. Missing 'metadata' field following a 'kind' field." \
+      && exit 1
     fi
   fi
 
