WIP Thu Apr 11 13:27:19 EDT 2019

diff --git a/upgraderator/cluster-fox b/upgraderator/cluster-fox
--- a/upgraderator/cluster-fox
+++ b/upgraderator/cluster-fox
@@ -34,7 +34,7 @@ azKubectl() {
   local az=$1
   shift
   local conf=$HOME/.kube/$az-config
-  if [ -f "$conf" ]; then echo "Missing kubectl configuration for $az. See copy-kubectl-config"; exit 1; fi
+  if [ ! -f "$conf" ]; then echo "Missing kubectl configuration for $az. See copy-kubectl-config."; exit 1; fi
   kubectl --kubeconf="$conf" $@
 }
 
