WIP Thu Apr 11 13:23:08 EDT 2019

diff --git a/upgraderator/cluster-fox b/upgraderator/cluster-fox
--- a/upgraderator/cluster-fox
+++ b/upgraderator/cluster-fox
@@ -34,7 +34,7 @@ azKubectl() {
   local az=$1
   shift
   local conf=$HOME/.kube/$az-config
-  if [ -f "$conf" ]; then echo "Missing kubectl configuration for $az. See copy-kubectl-config"; exit 1; done
+  if [ -f "$conf" ]; then echo "Missing kubectl configuration for $az. See copy-kubectl-config"; exit 1; fi
   kubectl --kubeconf="$conf" $@
 }
 
@@ -77,7 +77,7 @@ COMMAND=$1
 shift
 
 case $COMMAND in
-  kc) azKubectl $@
+  kc|kubectl) azKubectl $@
   list-masters) listMasters;;
   copy-kubectl-config) copyKubectlConfig;;
   *) usage "Unknown command: $COMMAND"
